name = "sonos-alarm"
main = "src/worker.js"
compatibility_date = "2024-12-01"

assets = { directory = "public" }

[triggers]
crons = ["* 5-10 * * *"]

[[kv_namespaces]]
binding = "TOKEN_KV"
id = "e6afdb3a372044079574cab4e8835ea4"
