name = "sonos-alarm"
main = "src/worker.js"
compatibility_date = "2024-12-01"

rules = [
  { type = "Text", globs = ["**/*.html"] },
  { type = "Text", globs = ["src/static/**/*.js"] },
  { type = "Text", globs = ["src/static/**/*.css"] }
]

[triggers]
crons = ["* 5-10 * * *", "* 21-23 * * *"]

[[kv_namespaces]]
binding = "TOKEN_KV"
id = "e6afdb3a372044079574cab4e8835ea4"
